// web/src/lib/components/ThemeToggle.svelte
<script lang="ts">
import { browser } from "$app/environment";
import { Monitor, Moon, Sun } from "@lucide/svelte";

type Theme = "light" | "dark" | "system";

let theme = $state<Theme>("system");

if (browser) {
  theme = (localStorage.getItem("theme") as Theme) ?? "system";
}

const nextTheme = $derived<Theme>(
  theme === "light" ? "dark" : theme === "dark" ? "system" : "light"
);

function applyTheme(t: Theme) {
  const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  const isDark = t === "dark" || (t === "system" && prefersDark);
  document.documentElement.classList.toggle("dark", isDark);
}

function toggle() {
  const next = nextTheme;

  const update = () => {
    theme = next;
    localStorage.setItem("theme", next);
    applyTheme(next);
  };

  if (document.startViewTransition) {
    document.startViewTransition(update);
  } else {
    update();
  }
}
</script>

<button
  onclick={toggle}
  class="cursor-pointer border-none rounded-md flex items-center justify-center p-2 scale-125
    text-muted-foreground hover:bg-muted bg-transparent transition-colors"
  aria-label="Toggle theme"
>
  {#if nextTheme === "dark"}
    <Moon size={18} />
  {:else if nextTheme === "system"}
    <Monitor size={18} />
  {:else}
    <Sun size={18} />
  {/if}
</button>

// web/src/components/ThemeToggle.tsx
import { useTheme } from "next-themes";
import { Button } from "@radix-ui/themes";
import { Sun, Moon, Monitor } from "lucide-react";
import { useMemo } from "react";

export function ThemeToggle() {
  const { theme, setTheme } = useTheme();

  const nextTheme = useMemo(() => {
    switch (theme) {
      case "light":
        return "dark";
      case "dark":
        return "system";
      case "system":
        return "light";
      default:
        console.error(`Invalid theme: ${theme}`);
        return "system";
    }
  }, [theme]);

  const icon = useMemo(() => {
    if (nextTheme === "system") {
      return <Monitor size={18} />;
    }
    return nextTheme === "dark" ? <Moon size={18} /> : <Sun size={18} />;
  }, [nextTheme]);

  return (
    <Button
      variant="ghost"
      size="3"
      onClick={() => setTheme(nextTheme)}
      style={{
        cursor: "pointer",
        backgroundColor: "transparent",
        border: "none",
        margin: "4px",
        padding: "7px",
        borderRadius: "6px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "var(--gray-11)",
        transition: "background-color 0.2s, color 0.2s",
        transform: "scale(1.25)",
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.backgroundColor = "var(--gray-4)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.backgroundColor = "transparent";
      }}
    >
      {icon}
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}
